=== quanghan-dev/prx_project/src/main/webapp/WEB-INF/project.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="project" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="project">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="language" type="xs:string"/>
                <xs:element name="sprint" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="sprint">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="duration" type="xs:string"/>
                <xs:element name="task" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>        
    </xs:element>
    
    <xs:element name="task">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="duration" type="xs:string"/>
                <xs:element name="status" type="xs:string"/>
                <xs:element name="manager"/>
                <xs:element name="employee" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>       
    </xs:element>
    
    <xs:element name="manager">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="deparment"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="employee">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="deparment"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="deparment">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== quanghan-dev/prx_project/src/main/webapp/WEB-INF/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<company xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="project.xsd">
    <project id="59ee53f3-69a6-4b21-ac6e-cf58629a76d4">
        <name>C100</name>
        <language>Java</language>
        <sprint id="5c30dcf0-3ae1-44d9-8e06-8990d9c48ca5">
            <name>#01</name>
            <duration>2021-2023</duration>
            <task id="651b6eb5-dc6e-4a8d-8fc7-7c843d5c51bd">
                <name>Create Stuff</name>
                <duration>20-10 - 31-10</duration>
                <status>Ongoing</status>
                <manager id="f01900b9-ae39-42ca-b904-fb2b9ca187f1">
                    <name>Jeff</name>
                    <department id="D001">
                        <name>Programming</name>
                    </department>
                </manager>
                <employeeAssigned>
                    <employee id="fde37db4-af14-4b55-bfc2-df6c1012ac4e">
                        <name>Steve</name>
                        <department id="D001">
                            <name>Programming</name>
                        </department>
                    </employee>
                    <employee id="9c5c57fc-0a84-4b29-8cc1-f713b1206d11">
                        <name>Hans</name>
                        <department id="D001">
                            <name>Programming</name>
                        </department>
                    </employee>
                </employeeAssigned>
            </task>
        </sprint>
        <sprint id="e5acc295-e1fa-4859-8d8f-236d24f90b72">
            <name>#02</name>
            <duration>2021-2023</duration>
            <task id="801453c1-fb89-4517-9e53-099be4b2ec45">
                <name>Create Stuff</name>
                <duration>20-10 - 31-10</duration>
                <status>On hold</status>
                <manager id="M002">
                    <name>Jones</name>
                    <department id="D002">
                        <name>Front-End</name>
                    </department>
                </manager>
                <employeeAssigned>
                    <employee id="0472d461-3728-4451-8dfb-ee62539e0781">
                        <name>Hades</name>
                        <department id="D002">
                            <name>Front-End</name>
                        </department>
                    </employee>
                    <employee id="3348dfac-e2bd-442c-a67e-28bd6132a02b">
                        <name>Zuck</name>
                        <department id="D002">
                            <name>Front-End</name>
                        </department>
                    </employee>
                </employeeAssigned>
            </task>
        </sprint>
    </project>
</company>
